server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/asnotdb
    username: postgres
    password: Test1234=
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
#        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
