server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/asnotdb
#    url: jdbc:h2:mem:db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
#    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
#        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
