server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/asnotdb
    username: postgres
    password: Test1234=
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
#      dialect: org.hibernate.dialect.PostgreSQL95Dialect

    show-sql: true

application:
  jwt:
    expiresAt: 846000
    headerPrefix: "Bearer "
    secret: "Y2nr@Svs1#Rume@v9^r$$hwTm563QpxLfdDTO$VdLLMnNRJmcQ"
    headerKey: "Authorization"
