server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/asnot_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
